In [1]:
import numpy as np

In [4]:
# generate some random data
data = np.random.randn(2, 3)
data

array([[-0.53866928, -0.29455803, -1.1086382 ],
       [ 0.23146288,  0.20743511,  0.43029942]])

然后进行数学运算：

In [5]:
data * 10

array([[ -5.38669284,  -2.94558031, -11.08638202],
       [  2.31462881,   2.07435108,   4.3029942 ]])

In [6]:
data + 1

array([[ 0.46133072,  0.70544197, -0.1086382 ],
       [ 1.23146288,  1.20743511,  1.43029942]])

## 创建ndarray

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为 `data2` 是列表的列表， `NumPy` 数组 `arr2` 的两个维度的 `shape` 是从 `data2` 引入的。可以用属性 `ndim` 和 `shape` 验证：